FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

ENV MODEL_PATH=/app/superkart_model.joblib
EXPOSE 7860

CMD ["python", "app.py"]