services:
  backend:
    build: ./backend_files
    ports:
      - "7860:7860"
    volumes:
      - type: bind
        source: ./backend_files/superkart_model.joblib
        target: /app/superkart_model.joblib
        read_only: true
        bind:
          create_host_path: false

  frontend:
    build: ./frontend_files
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: http://backend:7860
    depends_on:
      - backend